more additions

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -13,12 +13,12 @@ if [[ $EUID -eq 0 ]]; then
 fi
 
 # Check if git exists
-# if ! which git > /dev/null; then
-# 	echo " ───────────────────────────────────────────────────┐"
-# 	echo "         GIT NOT FOUND: Please install GIT           "
-# 	echo "└─────────────────────────────────────────────────── "
-# 	SystemExit
-# fi
+if ! which git > /dev/null; then
+	echo " ───────────────────────────────────────────────────┐"
+	echo "         GIT NOT FOUND: Please install GIT           "
+	echo "└─────────────────────────────────────────────────── "
+	SystemExit
+fi
 
 echo " ──────────────────────────────────────────────────┐"
 echo "            Acquiring sudo privileges               "
@@ -79,7 +79,7 @@ if which apt > /dev/null; then
 fi
 
 echo " ───────────────────────────────────────────────────┐"
-echo "       Installing 'PIP' Python package installer     "
+echo "        Installing PIP + Python Virtualenv           "
 echo "└─────────────────────────────────────────────────── "
 sudo -H pip install --upgrade pip
 sudo -H pip install --upgrade virtualenv
@@ -93,13 +93,17 @@ echo " ────────────────────────�
 echo "                Installing Hyperload                 "
 echo "└─────────────────────────────────────────────────── "
 git clone --depth=1 https://github.com/kammce/Hyperload.git $TOOLDIR/Hyperload/
+cd $TOOLDIR/Hyperload/
 $TOOLDIR/Hyperload/setup
+cd ../../
 
 echo " ───────────────────────────────────────────────────┐"
 echo "                Installing Telemetry                 "
 echo "└─────────────────────────────────────────────────── "
 git clone --depth=1 https://github.com/kammce/Telemetry.git $TOOLDIR/Telemetry
+cd $TOOLDIR/Hyperload/
 $TOOLDIR/Telemetry/setup
+cd ../../
 
 echo > env.sh <<END
 #!/bin/bash
@@ -136,6 +140,8 @@ export SJSUONEDEV
 export SJSUONEBAUD
 export MAKEFLAGS
 END
+
+cat env.sh
 
 echo
 echo " ──────────────────────────────────────────────────────────────┐"
